name: 签到脚本（每天10：30运行）

on:
  schedule:
    - cron: '30 10 * * *'  # 每天的 10:30 运行

jobs:
  qiandao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 准备 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 删除旧日志
        run: |
          rm -f py/log/qiandao/*.txt || true

      - name: 运行签到脚本
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          USER_COOKIE: ${{ secrets.USER_COOKIE }}
        run: |
          for file in py/py/qiandao/*.py;do
          py_name=$(basename $file .py)
          python "$file" > "py/log/qiandao/${py_name}.txt"
          done

    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if [[ `git status --porcelain` ]]; then
          git commit -m "每日签到" && git push
        else
        fi
