name: 更新iptv地址

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */48 * * *" # 每隔12h更新版本号


jobs:
  ollama-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 删除旧文件
      run: |
        rm -f iptv/iptv.m3u || true

    - name: 更新 iptv
      run: |
        curl -s "https://raw.githubusercontent.com/vbskycn/iptv/refs/heads/master/tv/iptv4.m3u" >> iptv/iptv.m3u

    - name: 推送更新
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if [[ `git status --porcelain` ]]; then
          git commit -m "iptv地址更新" && git push
        else
          echo "版本无变化。"
        fi
