name: 更新ollama版本

on:
  push:
  schedule:
    - cron: "0 */12 * * *" # 每隔12h更新版本号
  workflow_dispatch:

jobs:
  ollama-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 删除旧脚本
      run: |
        rm -f ollama/install.sh || true
        rm -f ollama/install-zh_CN.sh || true
        rm -f ollama/ollama-android.sh || true
        rm -f ollama/ollama-android-8b.sh || true

    - name: 运行 install.py
      run: python ollama/py/install.py > ollama.txt

    - name: 创建install.sh
      run: |
        cp ollama/install/install.sh.bak ollama/install.sh
        cp ollama/install/install-zh_CN.sh.bak ollama/install-zh_CN.sh
        cp ollama/install/ollama-android.sh.bak ollama/ollama-android.sh
        cp ollama/install/ollama-android-8b.sh.bak ollama/ollama-android-8b.sh

    - name: 更新 install.sh
      run: |
        OLLAMA=$(cat ollama.txt)
        sed -i "s/<version>/$OLLAMA/" ollama/install.sh
        sed -i "s/<version>/$OLLAMA/" ollama/install-zh_CN.sh

    - name: 更新 proxy
      run: |
        cp ollama/install/proxy.txt proxy.txt
        PROXY=$(cat proxy.txt)
        sed -i "s/<proxy_url>/$PROXY/" ollama/install.sh
        sed -i "s/<proxy_url>/$PROXY/" ollama/install-zh_CN.sh
        sed -i "s/<proxy_url>/$PROXY/" ollama/ollama-android.sh
        sed -i "s/<proxy_url>/$PROXY/" ollama/ollama-android-8b.sh
        
    - name: 删除ollama.txt
      run: |
        rm -f ollama.txt || true
        rm -f proxy.txt || true

    - name: 推送更新
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if [[ `git status --porcelain` ]]; then
          git commit -m "版本更新" && git push
        else
          echo "版本无变化。"
        fi
