name: 更新ollama版本

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *" # 每隔12h更新版本号


jobs:
  ollama-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 删除旧脚本
      run: |
        rm -f ollama/command.txt || true
        rm -f ollama/*.sh || true
        rm -f ollama/install/proxy.txt || true

    - name: 运行 install.py
      run: |
        python ollama/py/version.py > ollama.txt
        python proxy/proxy.py > ollama/install/proxy.txt
      

    - name: 创建install.sh
      run: |
        cp ollama/install/command.txt ollama/command.txt
        for file in *.sh.bak; do
        cp "$file" "ollama/${file%.bak}"
        done


    - name: 更新 install.sh
      run: |
        OLLAMA=$(cat ollama.txt)
        sed -i "s/<version>/$OLLAMA/" ollama/*.sh

    - name: 更新 proxy
      run: |
        PROXY=$(cat ollama/install/proxy.txt)
        sed -i "s|<proxy_url>|$PROXY|" ollama/command.txt
        sed -i "s|<proxy_url>|$PROXY|" ollama/*.sh
        
    - name: 删除ollama.txt
      run: |
        rm -f ollama.txt || true

    - name: 推送更新
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if [[ `git status --porcelain` ]]; then
          git commit -m "版本更新" && git push
        else
          echo "版本无变化。"
        fi
