name: ZTE 签到脚本（每天10：30运行）

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'  # 每天的 10:30 运行(UTC+8)

jobs:
  qiandao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 准备 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 删除旧日志
        run: |
          rm -f py/log/qiandao/zte.txt || true

      - name: 运行签到脚本
        env:
          USER_SIGN: ${{ secrets.USER_SIGN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_COOKIE: ${{ secrets.USER_COOKIE }}
        run: |
          python py/py/qiandao/zte.py > "py/log/qiandao/zte.txt"

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if [[ `git status --porcelain` ]]; then
            git commit -m "ZTE 每日签到" && git push
          else
            echo "ZTE 每日签到"
          fi
