name: 签到脚本（每天10：30运行）

on:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'  # 每天的 10:30 运行(UTC+8)

jobs:
  qiandao:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 准备 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 删除旧日志
        run: |
          rm -f py/log/qiandao/*.txt || true

      - name: 运行签到脚本
        env:
        # bark推送
          BARK_KEY: ${{ secrets.BARK_KEY }}
        # ZTE ENV
          USER_SIGN: ${{ secrets.USER_SIGN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_COOKIE: ${{ secrets.USER_COOKIE }}
        # jlc ENV
          JLC_ACCESSTOKEN: ${{ secrets.JLC_ACCESSTOKEN }}
        # znds ENV
          ZNDS_COOKIE: ${{ secrets.ZNDS_COOKIE }}
        run: |
          for file in py/py/qiandao/*.py;do
          py_name=$(basename $file .py)
          python "$file" > "py/log/qiandao/${py_name}.txt"
          done

      - name: 推送更新及署名
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if [[ `git status --porcelain` ]]; then
            git commit -m "每日签到" && git push
          else
            echo "每日签到"
          fi
